import { Opponents } from '../types/gameInterface';

export const opponents: Array<Opponents> = [
  { id: 1, name: 'John', surname: 'Smith', gender: 'male' },
  { id: 2, name: 'John', surname: ' Snow', gender: 'male' },
  { id: 3, name: 'Teresa', surname: ' Lynn', gender: 'female' },
  { id: 4, name: 'Nicole', surname: ' Madlen', gender: 'female' },
  { id: 5, name: 'Kristen', surname: ' Renee', gender: 'female' },
  { id: 6, name: 'Alan', surname: ' Mark', gender: 'male' },
  { id: 7, name: 'Kay', surname: ' Lynne', gender: 'male' },
  { id: 8, name: 'Mark', surname: ' Landgren', gender: 'male' },
  { id: 9, name: 'Eleanor', surname: ' Lee', gender: 'female' },
  { id: 10, name: 'Richard', surname: ' Carter', gender: 'male' },
  { id: 11, name: 'Krista', surname: ' Mar', gender: 'female' },
  { id: 12, name: 'Patricia', surname: ' Ann', gender: 'female' },
  { id: 13, name: 'Adam', surname: ' John', gender: 'male' },
  { id: 14, name: 'Adele', surname: ' Brown', gender: 'female' },
  { id: 15, name: 'Kathy', surname: ' Young', gender: 'male' },
  { id: 16, name: 'David', surname: ' Clinton', gender: 'male' },
  { id: 17, name: 'Angela', surname: ' Riley', gender: 'female' },
  { id: 18, name: 'Karla', surname: ' Puglisi', gender: 'female' },
  { id: 19, name: 'Antonio', surname: ' Neria', gender: 'male' },
  { id: 20, name: 'Lisa', surname: ' Adele', gender: 'female' },
  { id: 21, name: 'Debbie', surname: ' Reagan', gender: 'female' },
  { id: 22, name: 'Jose', surname: ' Hernandez', gender: 'male' },
  { id: 23, name: 'Arian', surname: ' Ray', gender: 'male' },
  { id: 24, name: 'Philip', surname: ' Hubanks', gender: 'male' },
  { id: 25, name: 'James', surname: ' Shelley', gender: 'male' },
  { id: 26, name: 'Kim', surname: ' Warren', gender: 'female' },
  { id: 27, name: 'Anaya', surname: ' Maria', gender: 'female' },
  { id: 28, name: 'Brittany', surname: ' Lane', gender: 'female' },
  { id: 29, name: 'Pardo', surname: ' Alcantar', gender: 'male' },
  { id: 30, name: 'Herbert', surname: ' Cumbaa', gender: 'male' },
  { id: 31, name: 'Scott', surname: ' Bartlett', gender: 'male' },
  { id: 32, name: 'Cheryl', surname: ' Turner', gender: 'female' },
  { id: 33, name: 'Amanda', surname: ' Greenwald', gender: 'male' },
];
